name: static-analysis

on:
  push:
  pull_request:

jobs:
  psalm:
    name: Psalm
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install Dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-dist --no-interaction --no-progress
      - name: Static Analysis
        continue-on-error: true
        run: vendor/bin/psalm --no-cache